# Generated by Django 4.1.4 on 2022-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=25, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
